function(add_imvk_graph_test name source)
  set(target imvk_graph_${name}_tests)
  add_executable(${target} graph/${source})
  target_link_libraries(${target} PRIVATE imvk)
  add_test(NAME imvk.graph.${name} COMMAND ${target})
endfunction()

add_imvk_graph_test(format_conversion_insertion FormatConversionInsertion.cpp)
add_imvk_graph_test(image_type_conversion_insertion
                    ImageTypeConversionInsertion.cpp)
add_imvk_graph_test(presentation Presentation.cpp)
add_imvk_graph_test(image_nodes ImageNodes.cpp)
add_imvk_graph_test(combine_image_conversions CombineImageConversions.cpp)
add_imvk_graph_test(compute_pass ComputePass.cpp)
add_imvk_graph_test(half_extents HalfExtents.cpp)
